package org.schabi.newpipe.gemini

import android.app.Activity
import android.content.Context
import android.content.ContextWrapper
import android.content.Intent
import android.os.Handler
import android.os.Looper
import android.view.Menu
import android.view.View
import android.widget.Toast
import androidx.preference.PreferenceManager
import com.google.android.exoplayer2.text.Cue
import com.google.android.exoplayer2.ui.SubtitleView
import org.schabi.newpipe.R
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.gemini.db.GeminiDatabase
import org.schabi.newpipe.gemini.manager.SubtitleTranslationManager
import org.schabi.newpipe.gemini.obj.SubtitleBlock
import org.schabi.newpipe.gemini.parser.SubtitleParser
import java.io.File
import java.util.Collections
import java.util.Locale
import java.util.concurrent.Executors

object GeminiSubtitleHelper {

    fun interface SubtitleReadyCallback {
        fun onSubtitlesReady(blocks: List<SubtitleBlock>)
    }

    fun interface PositionSupplier {
        fun getCurrentPosition(): Long
    }

    private val bgExecutor = Executors.newSingleThreadExecutor()
    private val mainHandler = Handler(Looper.getMainLooper())
    private var tickerRunnable: Runnable? = null
    private var activeBlocks: List<SubtitleBlock> = emptyList()
    private var activeManager: SubtitleTranslationManager? = null

    @JvmStatic
    fun addCaptionMenuItem(
        context: Context,
        parentActivity: Activity?,
        menu: Menu,
        groupId: Int,
        streamInfo: StreamInfo?,
        callback: SubtitleReadyCallback
    ) {
        if (streamInfo == null || streamInfo.subtitles.isNullOrEmpty()) return

        val videoId = streamInfo.url.substringAfterLast("v=").substringBefore("&").ifBlank { streamInfo.id }

        // Add 1-click translation items for each available subtitle track
        for (sub in streamInfo.subtitles) {
            val langName = sub.displayLanguageName ?: sub.languageTag ?: "Unknown"
            val title = if (sub.isAutoGenerated) {
                "✨ Translate $langName (auto) [Gemini]"
            } else {
                "✨ Translate $langName [Gemini]"
            }
            val menuItem = menu.add(groupId, Menu.NONE, Menu.NONE, title)
            menuItem.setIcon(R.drawable.ic_translate)
            menuItem.setOnMenuItemClickListener {
                startDirectTranslation(context, videoId, sub, callback)
                true
            }
        }

        // Add Export option
        val exportItem = menu.add(groupId, Menu.NONE, Menu.NONE, "📤 Export Subtitles (Gemini)")
        exportItem.setOnMenuItemClickListener {
            exportSubtitles(context, parentActivity, videoId)
            true
        }
    }

    @JvmStatic
    fun addCaptionMenuItem(
        context: Context,
        menu: Menu,
        groupId: Int,
        streamInfo: StreamInfo?,
        callback: SubtitleReadyCallback
    ) {
        addCaptionMenuItem(context, null, menu, groupId, streamInfo, callback)
    }

    private fun startDirectTranslation(
        context: Context,
        videoId: String,
        sub: SubtitlesStream,
        callback: SubtitleReadyCallback
    ) {
        val prefs = PreferenceManager.getDefaultSharedPreferences(context)
        val apiKey = prefs.getString("gemini_api_key", "")?.trim().orEmpty()
        if (apiKey.isEmpty()) {
            Toast.makeText(
                context,
                "⚠️ Lütfen önce Ayarlar -> Gemini AI Translation bölümünden Gemini API Key girin.",
                Toast.LENGTH_LONG
            ).show()
            return
        }

        val targetLocale = Locale.getDefault()
        val targetLangCode = targetLocale.language
        val langName = sub.displayLanguageName ?: sub.languageTag ?: "Auto"

        Toast.makeText(
            context,
            "✨ Gemini Çevirisi Başlatıldı ($langName -> ${targetLocale.displayLanguage})\n1. Chunk bekleniyor...",
            Toast.LENGTH_LONG
        ).show()

        activeManager?.cancel()
        val manager = SubtitleTranslationManager(context)
        activeManager = manager
        manager.setListener(object : SubtitleTranslationManager.TranslationListener {
            override fun onStateChanged(state: SubtitleTranslationManager.TranslationState) {}
            override fun onBlocksAvailable(blocks: List<SubtitleBlock>) {
                callback.onSubtitlesReady(blocks)
            }
        })
        manager.startTranslation(videoId, sub, targetLangCode)
    }

    private fun exportSubtitles(context: Context, activity: Activity?, videoId: String) {
        val dir = File(context.cacheDir, "gemini_subtitles")
        val rawFiles = dir.listFiles { file -> file.name.startsWith(videoId) }
        if (rawFiles.isNullOrEmpty()) {
            Toast.makeText(context, R.string.no_subtitles_to_export, Toast.LENGTH_SHORT).show()
            return
        }
        val latest = rawFiles.maxByOrNull { it.lastModified() } ?: return
        val sendIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "Subtitles - $videoId")
            putExtra(Intent.EXTRA_TEXT, latest.readText())
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
        }
        val chooser = Intent.createChooser(sendIntent, context.getString(R.string.export_subtitles)).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
        }
        context.startActivity(chooser)
    }

    @JvmStatic
    fun checkAndAutoLoadCachedSubtitles(
        context: Context,
        videoId: String?,
        callback: SubtitleReadyCallback
    ) {
        if (videoId.isNullOrBlank()) return

        val targetLang = Locale.getDefault().language
        bgExecutor.execute {
            try {
                val dao = GeminiDatabase.getInstance(context).translatedSubtitleDao()
                val cached = dao.getTranslatedChunksByVideo(videoId, targetLang)
                if (cached.isNotEmpty()) {
                    val allBlocks = mutableListOf<SubtitleBlock>()
                    for (item in cached) {
                        val parsed = SubtitleParser.parse(item.translatedSrtContent)
                        allBlocks.addAll(parsed)
                    }
                    if (allBlocks.isNotEmpty()) {
                        mainHandler.post {
                            callback.onSubtitlesReady(allBlocks)
                        }
                    }
                }
            } catch (_: Exception) {}
        }
    }

    @JvmStatic
    fun startLiveTicker(
        positionSupplier: PositionSupplier,
        subtitleView: SubtitleView?,
        blocks: List<SubtitleBlock>
    ) {
        stopLiveTicker()
        activeBlocks = blocks
        subtitleView?.visibility = View.VISIBLE

        tickerRunnable = object : Runnable {
            override fun run() {
                if (subtitleView != null && activeBlocks.isNotEmpty()) {
                    val pos = positionSupplier.getCurrentPosition()
                    val currentBlock = activeBlocks.firstOrNull { pos in it.startMs..it.endMs }
                    if (currentBlock != null) {
                        val cue = Cue.Builder().setText(currentBlock.text).build()
                        subtitleView.setCues(Collections.singletonList(cue))
                    } else {
                        subtitleView.setCues(Collections.emptyList())
                    }
                }
                mainHandler.postDelayed(this, 100)
            }
        }
        mainHandler.post(tickerRunnable!!)
    }

    @JvmStatic
    fun stopLiveTicker() {
        tickerRunnable?.let { mainHandler.removeCallbacks(it) }
        tickerRunnable = null
        activeBlocks = emptyList()
        activeManager?.cancel()
    }
}
