package org.schabi.newpipe.gemini

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.os.Handler
import android.os.Looper
import android.view.Menu
import android.view.View
import android.widget.Toast
import androidx.preference.PreferenceManager
import com.google.android.exoplayer2.text.Cue
import com.google.android.exoplayer2.ui.SubtitleView
import org.schabi.newpipe.R
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.gemini.db.GeminiDatabase
import org.schabi.newpipe.gemini.manager.SubtitleTranslationManager
import org.schabi.newpipe.gemini.obj.SubtitleBlock
import org.schabi.newpipe.gemini.parser.SubtitleParser
import java.io.File
import java.util.Collections
import java.util.Locale
import java.util.concurrent.Executors

object GeminiSubtitleHelper {

    fun interface SubtitleReadyCallback {
        fun onSubtitlesReady(blocks: List<SubtitleBlock>)
    }

    fun interface PositionSupplier {
        fun getCurrentPosition(): Long
    }

    private val bgExecutor = Executors.newSingleThreadExecutor()
    private val mainHandler = Handler(Looper.getMainLooper())
    private var tickerRunnable: Runnable? = null

    @Volatile
    private var activeBlocks: List<SubtitleBlock> = emptyList()

    @Volatile
    private var lastDisplayedText: String = ""

    private var activeManager: SubtitleTranslationManager? = null

    @JvmStatic
    fun addCaptionMenuItem(
        context: Context,
        parentActivity: Activity?,
        menu: Menu,
        groupId: Int,
        streamInfo: StreamInfo?,
        callback: SubtitleReadyCallback
    ) {
        if (streamInfo == null || streamInfo.subtitles.isNullOrEmpty()) return

        val videoId = streamInfo.url.substringAfterLast("v=").substringBefore("&").ifBlank { streamInfo.id }

        for (sub in streamInfo.subtitles) {
            val langName = sub.displayLanguageName ?: sub.languageTag ?: "Unknown"
            val title = if (sub.isAutoGenerated) {
                "✨ Translate $langName (auto) [Gemini]"
            } else {
                "✨ Translate $langName [Gemini]"
            }
            val menuItem = menu.add(groupId, Menu.NONE, Menu.NONE, title)
            menuItem.setIcon(R.drawable.ic_translate)
            menuItem.setOnMenuItemClickListener {
                startDirectTranslation(context, videoId, sub, callback)
                true
            }
        }

        val exportItem = menu.add(groupId, Menu.NONE, Menu.NONE, "📤 Export Subtitles (Gemini)")
        exportItem.setOnMenuItemClickListener {
            exportSubtitles(context, parentActivity, videoId)
            true
        }
    }

    @JvmStatic
    fun addCaptionMenuItem(
        context: Context,
        menu: Menu,
        groupId: Int,
        streamInfo: StreamInfo?,
        callback: SubtitleReadyCallback
    ) {
        addCaptionMenuItem(context, null, menu, groupId, streamInfo, callback)
    }

    private fun startDirectTranslation(
        context: Context,
        videoId: String,
        sub: SubtitlesStream,
        callback: SubtitleReadyCallback
    ) {
        val prefs = PreferenceManager.getDefaultSharedPreferences(context)
        val apiKey = prefs.getString("gemini_api_key", "")?.trim().orEmpty()
        if (apiKey.isEmpty()) {
            Toast.makeText(
                context,
                "⚠️ Lütfen önce Ayarlar -> Gemini AI Translation bölümünden Gemini API Key girin.",
                Toast.LENGTH_LONG
            ).show()
            return
        }

        val targetLocale = Locale.getDefault()
        val targetLangCode = targetLocale.language
        val langName = sub.displayLanguageName ?: sub.languageTag ?: "Auto"

        Toast.makeText(
            context,
            "✨ Gemini Çevirisi Başlatıldı ($langName -> ${targetLocale.displayLanguage})\n1. Chunk bekleniyor...",
            Toast.LENGTH_LONG
        ).show()

        activeManager?.cancel()
        val manager = SubtitleTranslationManager(context)
        activeManager = manager
        manager.setListener(object : SubtitleTranslationManager.TranslationListener {
            override fun onStateChanged(state: SubtitleTranslationManager.TranslationState) {}
            override fun onBlocksAvailable(blocks: List<SubtitleBlock>) {
                updateActiveBlocks(blocks)
                callback.onSubtitlesReady(blocks)
            }
        })
        manager.startTranslation(videoId, sub, targetLangCode)
    }

    private fun exportSubtitles(context: Context, activity: Activity?, videoId: String) {
        val dir = File(context.cacheDir, "gemini_subtitles")
        val rawFiles = dir.listFiles { file -> file.name.startsWith(videoId) }
        if (rawFiles.isNullOrEmpty()) {
            Toast.makeText(context, R.string.no_subtitles_to_export, Toast.LENGTH_SHORT).show()
            return
        }
        val latest = rawFiles.maxByOrNull { it.lastModified() } ?: return
        val sendIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "Subtitles - $videoId")
            putExtra(Intent.EXTRA_TEXT, latest.readText())
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
        }
        val chooser = Intent.createChooser(sendIntent, context.getString(R.string.export_subtitles)).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
        }
        context.startActivity(chooser)
    }

    @JvmStatic
    fun checkAndAutoLoadCachedSubtitles(
        context: Context,
        streamInfo: StreamInfo?,
        callback: SubtitleReadyCallback
    ) {
        if (streamInfo == null) return
        val videoId = streamInfo.url.substringAfterLast("v=").substringBefore("&").ifBlank { streamInfo.id }
        if (videoId.isBlank()) return

        val targetLang = Locale.getDefault().language
        bgExecutor.execute {
            try {
                val dao = GeminiDatabase.getInstance(context).translatedSubtitleDao()
                val cached = dao.getTranslatedChunksByVideo(videoId, targetLang)
                if (cached.isNotEmpty()) {
                    val allBlocks = mutableListOf<SubtitleBlock>()
                    for (item in cached) {
                        val parsed = SubtitleParser.parse(item.translatedSrtContent)
                        allBlocks.addAll(parsed)
                    }
                    if (allBlocks.isNotEmpty()) {
                        mainHandler.post {
                            updateActiveBlocks(allBlocks)
                            callback.onSubtitlesReady(allBlocks)
                        }
                    }

                    val first = cached.first()
                    val totalChunks = first.totalChunks
                    if (cached.size < totalChunks && !streamInfo.subtitles.isNullOrEmpty()) {
                        val sourceSub = streamInfo.subtitles.firstOrNull { it.languageTag == first.sourceLanguage }
                            ?: streamInfo.subtitles.firstOrNull { !it.isAutoGenerated }
                            ?: streamInfo.subtitles.first()

                        mainHandler.post {
                            activeManager?.cancel()
                            val manager = SubtitleTranslationManager(context)
                            activeManager = manager
                            manager.setListener(object : SubtitleTranslationManager.TranslationListener {
                                override fun onStateChanged(state: SubtitleTranslationManager.TranslationState) {}
                                override fun onBlocksAvailable(blocks: List<SubtitleBlock>) {
                                    updateActiveBlocks(blocks)
                                    callback.onSubtitlesReady(blocks)
                                }
                            })
                            manager.startTranslation(videoId, sourceSub, targetLang)
                        }
                    }
                }
            } catch (_: Exception) {}
        }
    }

    @JvmStatic
    fun checkAndAutoLoadCachedSubtitles(
        context: Context,
        videoId: String?,
        callback: SubtitleReadyCallback
    ) {
        if (videoId.isNullOrBlank()) return

        val targetLang = Locale.getDefault().language
        bgExecutor.execute {
            try {
                val dao = GeminiDatabase.getInstance(context).translatedSubtitleDao()
                val cached = dao.getTranslatedChunksByVideo(videoId, targetLang)
                if (cached.isNotEmpty()) {
                    val allBlocks = mutableListOf<SubtitleBlock>()
                    for (item in cached) {
                        val parsed = SubtitleParser.parse(item.translatedSrtContent)
                        allBlocks.addAll(parsed)
                    }
                    if (allBlocks.isNotEmpty()) {
                        mainHandler.post {
                            updateActiveBlocks(allBlocks)
                            callback.onSubtitlesReady(allBlocks)
                        }
                    }
                }
            } catch (_: Exception) {}
        }
    }

    @Synchronized
    private fun updateActiveBlocks(blocks: List<SubtitleBlock>) {
        activeBlocks = SubtitleBlock.mergeOverlapping(blocks).sortedBy { it.startMs }
        lastDisplayedText = ""
    }

    /**
     * Restart ticker with a new SubtitleView (e.g. after player recreation).
     * Uses preserved activeBlocks if available — no need to wait for cache reload.
     */
    @JvmStatic
    fun restartTickerWithView(
        positionSupplier: PositionSupplier,
        subtitleView: SubtitleView?
    ) {
        if (activeBlocks.isEmpty()) return
        stopTickerOnly()
        startLiveTicker(positionSupplier, subtitleView, activeBlocks)
    }

    @JvmStatic
    fun startLiveTicker(
        positionSupplier: PositionSupplier,
        subtitleView: SubtitleView?,
        blocks: List<SubtitleBlock>
    ) {
        stopTickerOnly()
        updateActiveBlocks(blocks)
        subtitleView?.visibility = View.VISIBLE

        tickerRunnable = object : Runnable {
            override fun run() {
                try {
                    if (subtitleView != null && activeBlocks.isNotEmpty()) {
                        val pos = positionSupplier.getCurrentPosition()

                        val prefs = subtitleView.context?.let {
                            PreferenceManager.getDefaultSharedPreferences(it)
                        }

                        val timeOffsetMs = prefs?.getString("gemini_subtitle_time_offset", "0")
                            ?.toLongOrNull() ?: 0L
                        val adjustedPos = (pos + timeOffsetMs).coerceAtLeast(0L)

                        val currentBlock = SubtitleBlock.findActiveBlock(activeBlocks, adjustedPos)

                        if (currentBlock != null) {
                            if (currentBlock.text != lastDisplayedText) {
                                val cue = buildStyledCue(subtitleView, currentBlock.text)
                                subtitleView.setCues(Collections.singletonList(cue))
                                lastDisplayedText = currentBlock.text
                            }
                        } else if (lastDisplayedText.isNotEmpty()) {
                            subtitleView.setCues(Collections.emptyList())
                            lastDisplayedText = ""
                        }
                    }
                } catch (_: Exception) {
                    // Swallow to keep ticker alive
                }
                mainHandler.postDelayed(this, 50)
            }
        }
        mainHandler.post(tickerRunnable!!)
    }

    private fun buildStyledCue(subtitleView: SubtitleView, text: String): Cue {
        val context = subtitleView.context ?: return Cue.Builder().setText(text).build()

        val prefs = PreferenceManager.getDefaultSharedPreferences(context)

        val position = prefs.getString("gemini_subtitle_position", "bottom") ?: "bottom"
        val yPercentage = when (position) {
            "top" -> 0.05f
            "middle" -> 0.45f
            else -> 0.90f
        }

        val sizeScale = prefs.getString("gemini_subtitle_size", "1.0")
            ?.toFloatOrNull() ?: 1.0f
        val scaledFraction = SubtitleView.DEFAULT_TEXT_SIZE_FRACTION * sizeScale

        subtitleView.setFractionalTextSize(scaledFraction)

        return Cue.Builder()
            .setText(text)
            .setLine(yPercentage, Cue.LINE_TYPE_FRACTION)
            .build()
    }

    /** Stop ticker only — preserve activeBlocks for player recreation */
    private fun stopTickerOnly() {
        tickerRunnable?.let { mainHandler.removeCallbacks(it) }
        tickerRunnable = null
        lastDisplayedText = ""
    }

    /** Stop ticker AND clear everything (used when subtitles are turned off) */
    @JvmStatic
    fun stopLiveTicker() {
        stopTickerOnly()
        activeBlocks = emptyList()
        activeManager?.cancel()
    }
}
